# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib geneplot
#' @importFrom Rcpp sourceCpp
NULL

double_sum <- function(nu) {
    .Call('_geneplot_double_sum', PACKAGE = 'geneplot', nu)
}

int_sum <- function(nu) {
    .Call('_geneplot_int_sum', PACKAGE = 'geneplot', nu)
}

rcpp_calc_dist <- function(nu, leave_one_out = FALSE, differenceLGPs = FALSE) {
    .Call('_geneplot_rcpp_calc_dist', PACKAGE = 'geneplot', nu, leave_one_out, differenceLGPs)
}

rcpp_calc_min_beta <- function(nu_mat) {
    .Call('_geneplot_rcpp_calc_min_beta', PACKAGE = 'geneplot', nu_mat)
}

rcpp_calc_max_beta <- function(nu_mat) {
    .Call('_geneplot_rcpp_calc_max_beta', PACKAGE = 'geneplot', nu_mat)
}

rcpp_calc_multi_locus_dist <- function(nutab, leave_one_out = FALSE, differenceLGPs = FALSE) {
    .Call('_geneplot_rcpp_calc_multi_locus_dist', PACKAGE = 'geneplot', nutab, leave_one_out, differenceLGPs)
}

rcpp_calc_multi_locus_K <- function(dist, s) {
    .Call('_geneplot_rcpp_calc_multi_locus_K', PACKAGE = 'geneplot', dist, s)
}

rcpp_calc_multi_locus_K1 <- function(dist, s) {
    .Call('_geneplot_rcpp_calc_multi_locus_K1', PACKAGE = 'geneplot', dist, s)
}

rcpp_calc_multi_locus_K2 <- function(dist, s) {
    .Call('_geneplot_rcpp_calc_multi_locus_K2', PACKAGE = 'geneplot', dist, s)
}

rcpp_calc_multi_locus_K3 <- function(dist, s) {
    .Call('_geneplot_rcpp_calc_multi_locus_K3', PACKAGE = 'geneplot', dist, s)
}

rcpp_calc_mu <- function(dist) {
    .Call('_geneplot_rcpp_calc_mu', PACKAGE = 'geneplot', dist)
}

rcpp_calc_sigma <- function(dist) {
    .Call('_geneplot_rcpp_calc_sigma', PACKAGE = 'geneplot', dist)
}

rcpp_calc_what <- function(x, sh, dist, use_x = FALSE) {
    .Call('_geneplot_rcpp_calc_what', PACKAGE = 'geneplot', x, sh, dist, use_x)
}

rcpp_calc_uhat <- function(sh, dist) {
    .Call('_geneplot_rcpp_calc_uhat', PACKAGE = 'geneplot', sh, dist)
}

rcpp_calc_shat <- function(x, dist) {
    .Call('_geneplot_rcpp_calc_shat', PACKAGE = 'geneplot', x, dist)
}

rcpp_calc_fhat <- function(x_vec, dist, min_dist, max_dist, mean_dist, logten = FALSE) {
    .Call('_geneplot_rcpp_calc_fhat', PACKAGE = 'geneplot', x_vec, dist, min_dist, max_dist, mean_dist, logten)
}

rcpp_calc_Fhat <- function(x_vec, dist, min_dist, max_dist, mean_dist, logten = FALSE, use_x = FALSE) {
    .Call('_geneplot_rcpp_calc_Fhat', PACKAGE = 'geneplot', x_vec, dist, min_dist, max_dist, mean_dist, logten, use_x)
}

rcpp_calc_qsearch_params <- function(dist, min_dist, max_dist, sh_tol = 1e-4, max_quantile = 0.995, logten = FALSE) {
    .Call('_geneplot_rcpp_calc_qsearch_params', PACKAGE = 'geneplot', dist, min_dist, max_dist, sh_tol, max_quantile, logten)
}

rcpp_calc_Qhat <- function(y, Fhat_qsearch_params, nutab, logten = FALSE) {
    .Call('_geneplot_rcpp_calc_Qhat', PACKAGE = 'geneplot', y, Fhat_qsearch_params, nutab, logten)
}

